### PR TITLE
PythonCompiler: use classmethod instead

### PR DESCRIPTION
**Pull request by antonv6**
(again, not tested, but is hopefully simple enough)

Is there a guide for running test suite? Or better yet, can we get CI?

### CODE REVIEW

**Comment by antonv6** [comment]
Come to think of it, it's probably better to move this method to the KaitaiStruct itself. But since runtime and compiler are two different repos, I can't be sure it won't break anything. Tests would help.

Oh, and don't forget to update http://kaitai.io/repl/

**Comment by GreyCat** [comment]
Tests are available in separate [tests] repo and [guide] is actually right there, in README. For Python, it boils down to `./build-compiler && ./build-formats && ./run-python`.

CI is available too, but, as you've mentioned, there are many different repositories, it requires a commit into [central repo], then [Travis] will do the job.

Tests results are published at http://kaitai.io/ci in a concise summary table.

[tests]: https://github.com/kaitai-io/kaitai_struct_tests
[guide]: https://github.com/kaitai-io/kaitai_struct_tests#how-to-test
[central repo]: https://github.com/kaitai-io/kaitai_struct_tests
[Travis]: https://travis-ci.org/kaitai-io/kaitai_struct

**Comment by GreyCat** [comment]
I've checked that the tests pass. Do you still want this to be committed, or you've decided to move it into runtime?

**Comment by antonv6** [comment]
I guess, it's still an improvement. I do plan to take a look at the runtime and move it there if possible, just not today.

**Comment by GreyCat** [comment]
Ok, thanks!

**Pull request merged**
