### PR TITLE
python translator fixed reversing and substring for concatenated inputs

### PR DESCRIPTION
**Pull request by smarek**
fixes test_expr_ops_parens.py

### CODE REVIEW

**Comment by generalmimon** [comment]
@smarek Thanks for the contribution, merging in!

**Comment by generalmimon** [comment]
@smarek In an hour (tomorrow ~0:45) should finish the CI build (running in [Travis CI](https://travis-ci.org/github/kaitai-io/ci_targets)), so you should be able to watch the CI dashboard at https://ci.kaitai.io/ if this change actually fixed the test `ExprOpsParens` for Python.

**Comment by generalmimon** [comment]
And the change is already deployed at https://ide.kaitai.io/devel/, so you can review manually (by generating a parser to a custom language: see [Web IDE Wiki](https://github.com/kaitai-io/kaitai_struct_webide/wiki/Features#generate-file-parser-for-your-favorite-language)) if it works as intended.

**Comment by smarek** [comment]
Looks like CI is happy, and I'm happy too :)

**Pull request merged**
