### PR TITLE
Pep8

### PR DESCRIPTION
**Pull request by antonv6**
A couple of style fixes for generated python code (not tested, but should be simple enough).

### CODE REVIEW

**Comment by GreyCat** [comment]
Thanks!

**Comment by GreyCat** [comment]
Sorry, I thought I've merged it before closing, looks like something went wrong. Now it should be merged properly.

Thanks again!

**Comment by GreyCat** [comment]
By the way, would you be interested in doing more audit of Python generated code & runtime? I'm by no means an expert in Python, so probably there's lots of room for improvement.

**Comment by antonv6** [comment]
Sure, I can take a look once in a while.

**Pull request merged**
