### PR TITLE
Changed the dependency in the file

### PR DESCRIPTION
**Pull request by KOLANICH**

### CODE REVIEW

**Comment by GreyCat** [comment]
Please provide your rationale. This particular setting was chosen after a long discussion in sbt.

**Comment by KOLANICH** [comment]
The rationale not to install an obsolete version of java to modern versions of distros. IMHO this case is itself too restrictive: there are impls of java having other package name. Could you give me a link to the discussion you have meant?

**Comment by GreyCat** [comment]
Contrary to what it might suggest, `java8-runtime-headless` does not install "obsolete version of java", but rather requires any JRE 8+ to be present on the system. I.e. if you have either Oracle's or OpenJDK build of Java 10, it should work and not force you to install actual JRE 8.

Here's the discussion: https://github.com/sbt/sbt-native-packager/issues/1106

**Comment by KOLANICH** [comment]
That's nice. Thank you for the info.

**Pull request closed without merging**
