### PR TITLE
Added Lua support

### PR DESCRIPTION
**Pull request by adrianherrera**
Hi there!

I wrote a Lua backend for Kaitai Struct. I also have a PR for tests. The runtime is available at https://github.com/adrianherrera/kaitai_struct_lua_runtime

### CODE REVIEW

**Comment by GreyCat** [comment]
Wow. Just wow ;) I'm truly speechless. Thanks! Going to test it now...

**Comment by GreyCat** [comment]
I've sent you the invitation to kaitai-io organization. Can I ask you to accept it and then push "Transfer" button in settings of https://github.com/adrianherrera/kaitai_struct_lua_runtime, to transfer it clearly to kaitai-io, so it would become https://github.com/kaitai-io/kaitai_struct_lua_runtime?

Can't wait to integrate this into our CI ;)

**Comment by adrianherrera** [comment]
Transfer is done!

**Comment by Freed-Wu** [comment]
Currently, ksc generate lua code with global variables.

```lua
require "kaitaistruct"

User = class.class(KaitaiStruct)
```

It will waste global name space. Why not use `local`:

```lua
local KaitaiStruct = require "kaitaistruct"[1]

local User = class.class(KaitaiStruct)

return User
```

**Comment by generalmimon** [comment]
@Freed-Wu Please open a new issue in https://github.com/kaitai-io/kaitai_struct/issues - this is not the right place.

**Pull request merged**
