### PR TITLE
Enum inverse map

### PR DESCRIPTION
**Pull request by ams-tschoening**
"enumToInt" didn't take the fully qualified path of an ENUM into account when rendering usage of the associated inverse map. If that map needed to be accessed in some external KSY compared to where the map is hosted, things failed because the map was wrongly assumed to be in the KSY where it is used. This commit changes "I__ENUM" to "Class::I__ENUM" following what has been available already as "enumDirectMap".

I've additionally added some logging for resolving ENUMs to make debugging easier following the approaches already available for types and because similar debugging statements where already available, only commented.

This fixes https://github.com/kaitai-io/kaitai_struct/issues/552.

### CODE REVIEW

**Comment by ams-tschoening** [comment]
I would like to maintain some debugging log files and here seems a good place to do so.

[Dokument1.txt](https://github.com/kaitai-io/kaitai_struct_compiler/files/3049126/Dokument1.txt)
[Dokument2.txt](https://github.com/kaitai-io/kaitai_struct_compiler/files/3049127/Dokument2.txt)

**Comment by ams-tschoening** [comment]
Any interest to review/merge?

**Comment by GreyCat** [comment]
Works perfect! My big thanks for pointing out this problem and contributing a solution! Sorry for this review taking so long, merging in.

**Comment by GreyCat** [comment]
I went ahead and converted your spec to KST, generating the rest of the specs for other languages.

Most languages worked fine, but C++ seems to fail building the format with:

```
In file included from /home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.cpp:4:
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:18:32: error: unknown type name 'enum_to_i_class_border_1_t'; did you mean 'enum_to_i_class_border_2_t'?
    enum_to_i_class_border_2_t(enum_to_i_class_border_1_t* p_parent, kaitai::kstream* p__io, kaitai::kstruct* p__parent = nullptr, enum_to_i_class_border_2_t* p__root = nullptr);
                               ^~~~~~~~~~~~~~~~~~~~~~~~~~
                               enum_to_i_class_border_2_t
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:14:7: note: 'enum_to_i_class_border_2_t' declared here
class enum_to_i_class_border_2_t : public kaitai::kstruct {
      ^
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:34:5: error: unknown type name 'enum_to_i_class_border_1_t'; did you mean 'enum_to_i_class_border_2_t'?
    enum_to_i_class_border_1_t* m_parent;
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
    enum_to_i_class_border_2_t
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:14:7: note: 'enum_to_i_class_border_2_t' declared here
class enum_to_i_class_border_2_t : public kaitai::kstruct {
      ^
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:39:5: error: unknown type name 'enum_to_i_class_border_1_t'; did you mean 'enum_to_i_class_border_2_t'?
    enum_to_i_class_border_1_t* parent() const { return m_parent; }
    ^~~~~~~~~~~~~~~~~~~~~~~~~~
    enum_to_i_class_border_2_t
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:14:7: note: 'enum_to_i_class_border_2_t' declared here
class enum_to_i_class_border_2_t : public kaitai::kstruct {
      ^
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.cpp:8:56: error: unknown type name 'enum_to_i_class_border_1_t'; did you mean 'enum_to_i_class_border_2_t'?
enum_to_i_class_border_2_t::enum_to_i_class_border_2_t(enum_to_i_class_border_1_t* p_parent, kaitai::kstream* p__io, kaitai::kstruct* p__parent, enum_to_i_class_border_2_t* p__root) : kaitai::kstruct(p__io) {
                                                       ^~~~~~~~~~~~~~~~~~~~~~~~~~
                                                       enum_to_i_class_border_2_t
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.h:14:7: note: 'enum_to_i_class_border_2_t' declared here
class enum_to_i_class_border_2_t : public kaitai::kstruct {
      ^
/home/travis/build/kaitai-io/ci_targets/tests/compiled/cpp_stl_11/enum_to_i_class_border_2.cpp:25:26: error: no member named 'some_dog' in 'enum_to_i_class_border_2_t'
    m_is_dog = parent()->some_dog() == 4;
               ~~~~~~~~  ^
```

**Pull request merged**
